title: Curriculum Vitae
url: 'https://kristofstroobants.github.io/cv'
baseurl: "" # set baseurl to empty for direct asset resolution


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3 groen
style: storyboard
#style: styles-5 oranje
#style: styles-6 


#Profile information
name: Kristof Stroobants
status: HIRED
focus: CLOUD / AUTOMATION / AI
pic: profile-ghibli.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: kristofstroobants@gmail.com
website: kristofstroobants.github.io #do not add http://
linkedin: kristof-stroobants-1220106
github: kristofstroobants
#twitter: 'CoekieCrumbles'

#Update all the sections by editing the files inside _includes folder.
